# Generated by Django 4.0 on 2021-12-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resto',
            name='halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resto',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='resto',
            name='specialite',
            field=models.ManyToManyField(blank=True, related_name='spec_list', to='api.Specialite'),
        ),
        migrations.AlterField(
            model_name='resto',
            name='tripadvisor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='resto',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
