# Generated by Django 4.0 on 2021-12-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_resto_halal_alter_resto_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resto',
            name='specialite',
        ),
        migrations.AddField(
            model_name='resto',
            name='specialites',
            field=models.ManyToManyField(blank=True, related_name='restos', to='api.Specialite'),
        ),
    ]
