# Generated by Django 4.0 on 2022-05-11 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0003_remove_resto_specialite_resto_specialites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resto',
            name='specialites',
            field=models.ManyToManyField(blank=True, null=True, related_name='restos', to='api.Specialite'),
        ),
        migrations.AlterField(
            model_name='resto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
